### ISSUE TITLE
Ensure Gradle 7.x compatibility

### ISSUE THREAD

**Issue by reinhapa** [bmuschko/gradle-izpack-plugin#16]
@bmuschko  Is it possible to create a new revision of the plugin in order to be usable with Gradle 7.0?

**Comment by bmuschko** [comment]
What exactly is broken? Please provide a stack trace. I am heavily relying to the community to help out here. Could you please provide a pull request?

**Comment by reinhapa** [comment]
Actually you already fixed it on the master branch with [this commit](https://github.com/bmuschko/gradle-izpack-plugin/commit/a356586220b0243f8e2e45415d4b8f49cde1f51c) causing the following failure when using Gradle 7.0

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':Installer:products:newdb:izPackCreateInstaller' (type 'CreateInstallerTask').
  - Type 'CreateInstallerTask' property 'outputFile' is annotated with @PathSensitive but that is not allowed for 'OutputFile' properties.
    
    Reason: This modifier is used in conjunction with a property of type 'OutputFile' but this doesn't have semantics.
    
    Possible solution: Remove the '@PathSensitive' annotation.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#incompatible_annotations for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by bmuschko** [comment]
I did? Interesting. :-) Yeah, I will look into release a new version. Will require a bunch of other changes as Bintray JCenter will go away soon.

**Comment by reinhapa** [comment]
@bmuschko thanks for looking into this, sorry to not be more of a help 😏

**Comment by bmuschko** [comment]
A new version has been released.
