### ISSUE TITLE
usage with izpack v 5

### ISSUE THREAD

**Issue by maiklos** [bmuschko/gradle-izpack-plugin#5]
it seems that is not possible to use izpack version 5 with this plugin.
There is no izpack-standalone-compiler for version 5.

**Comment by AndyBowes** [comment]
Hi Benjamin
We are looking to migrate from izPack v4.3.5 to v5.0.5.  At the moment we are using gradle-izpack-plugin:0.2.3 which doesn't support izPack v5.0.5.

Is the best approach to invoke the izPack Ant task from the Gradle script? (Similar to the Cargo Ant task in your Gradle in Action book)

**Comment by bmuschko** [comment]
@AndyBowes Yes, exactly. That's pretty much what this plugin does as well.

**Comment by bradcfisher** [comment]
Izpack pull request [#408](https://github.com/izpack/izpack/pull/408) resolves an issue with providing the configuration XML directly to the ant task.  It will fix the incompatibility with izPack 5, and the only change required in the build.gradle should be to update the dependency:

```
izpack 'org.codehaus.izpack:izpack-ant:5.0.7'
```

(Of course, that's assuming the pull request is merged into 5.0.7)

**Comment by rkrell** [comment]
It has been merged, thank you again, @bradcfisher, for fixing this.

**Comment by bmuschko** [comment]
@bradcfisher Thanks! I'll close this issue.

**Comment by pradeepggowda** [comment]
For those of you who are facing issues in adding izPack 5.x.x to gradle make these settings to your build.gradle file

repositories {
    mavenCentral()

    jcenter()

    maven {
        // For IcePDF distributions
        name "Ice Maven Release Repository"
        url "http://anonsvn.icesoft.org/repo/maven2/releases"
    }
}

dependencies {
    izpack 'org.codehaus.izpack:izpack-ant:5.1.3'
}

and then tada, it works.
